name: Scheduled Run

on:
  schedule:
    - cron: '* * * * *'  # runs at 9:30 AM IST

jobs:
  log-event:
    runs-on: ubuntu-latest
    steps:
      - name: Scheduled job
        run: echo "Scheduled cron job ran"
